apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: abhishekchandel/nagp-k8s-assignment-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-db
        - name: MONGO_COLLECTION
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-collection
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000