name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push multi-architecture image
      uses: docker/build-push-action@v5
      with:
        context: ./webapp
        file: ./webapp/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          abhishekchandelnag/k8s-assignment-app:latest
          abhishekchandelnag/k8s-assignment-app:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
